nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php-fpm"
    volumes:
      - e:/WorkSpace/www:/data
      - e:/WorkSpace/conf/nginx:/etc/nginx/conf.d
php-fpm:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "docker_redis"
    volumes:
      - e:/WorkSpace/www:/data
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - e:/WorkSpace/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
docker_redis:
    build: ./redis
    ports:
      - "6379:6379"