nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - e:/webroot:/data
      - e:/docker_dev/nginx/vhosts:/etc/nginx/conf.d
php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - e:/webroot:/data
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - e:/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
redis:
    build: ./redis
    ports:
      - "6379:6379"