nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /workspace:/opt
php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - /workspace:/opt
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /workspace/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
redis:
    build: ./redis
    ports:
      - "6379:6379"